# Generated by Django 6.0.3 on 2026-03-19 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orcamento', models.CharField(blank=True, max_length=40, null=True)),
                ('revisao', models.PositiveIntegerField(default=0)),
                ('is_revisao', models.BooleanField(default=False)),
                ('is_ativo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Não Enviado', 'Não Enviado'), ('Aguardando Aprovação', 'Aguardando Aprovação'), ('Aprovado', 'Aprovado'), ('Reprogramado', 'Reprogramado'), ('Cancelado', 'Cancelado'), ('Concluído', 'Concluído'), ('Desativado', 'Desativado')], default='Não Enviado', max_length=30)),
                ('enviado', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('orcamento_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='orcamentos.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=60)),
                ('status_de', models.CharField(blank=True, max_length=30, null=True)),
                ('status_para', models.CharField(blank=True, max_length=30, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_logs', to=settings.AUTH_USER_MODEL)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='orcamentos.orcamento')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['orcamento_original', 'revisao'], name='orcamentos__orcamen_e5a081_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['orcamento_original', 'is_ativo'], name='orcamentos__orcamen_c33f51_idx'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status'], name='orcamentos__status_3e1d3f_idx'),
        ),
    ]
